version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  target-branch: auto-dep-updates
  labels:
  - ":robot: bot"
  ignore:
  - dependency-name: "@buildit/eslint-config"
    versions:
    - ">= 0"
  - dependency-name: "@buildit/gravity-ui-nunjucks"
    versions:
    - ">= 0"
  - dependency-name: "@buildit/gravity-ui-web"
    versions:
    - ">= 0"
  - dependency-name: "@buildit/semantic-release"
    versions:
    - ">= 0"
  - dependency-name: "@buildit/semantic-release-lerna-analyzer"
    versions:
    - ">= 0"
  - dependency-name: "@buildit/semantic-release-lerna-release-notes-generator"
    versions:
    - ">= 0"
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.41
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.1
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: ts-jest
    versions:
    - 26.4.4
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: "@commitlint/travis-cli"
    versions:
    - 11.0.0
    - 12.0.0
    - 12.0.1
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 11.0.0
    - 12.0.0
    - 12.0.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
  - dependency-name: node-notifier
    versions:
    - 8.0.1
