version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    target_branch: "auto-dep-updates"
    default_labels:
      - ":robot: bot"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
    ignored_updates:
      - match:
          dependency_name: "@buildit/eslint-config"
      - match:
          dependency_name: "@buildit/semantic-release"
      - match:
          dependency_name: "@buildit/semantic-release-lerna-analyzer"
      - match:
          dependency_name: "@buildit/semantic-release-lerna-release-notes-generator"
      - match:
          dependency_name: "@buildit/gravity-ui-web"
      - match:
          dependency_name: "@buildit/gravity-ui-nunjucks"
